apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: ashutosh3309/kube-vol-demo:v2
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: story-config
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-vol
      volumes:
        - name: story-vol
          persistentVolumeClaim:
            claimName: story-pvc